# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io_gphoto2.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='io_gphoto2.proto',
  package='io_gphoto2',
  serialized_pb='\n\x10io_gphoto2.proto\x12\nio_gphoto2\"D\n\x05Photo\x12\r\n\x05\x62ytes\x18\x01 \x02(\t\x12\x0e\n\x06size_x\x18\x02 \x02(\x05\x12\x0e\n\x06size_y\x18\x03 \x02(\x05\x12\x0c\n\x04type\x18\x04 \x02(\t')




_PHOTO = _descriptor.Descriptor(
  name='Photo',
  full_name='io_gphoto2.Photo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bytes', full_name='io_gphoto2.Photo.bytes', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='size_x', full_name='io_gphoto2.Photo.size_x', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='size_y', full_name='io_gphoto2.Photo.size_y', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='io_gphoto2.Photo.type', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=32,
  serialized_end=100,
)

DESCRIPTOR.message_types_by_name['Photo'] = _PHOTO

class Photo(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PHOTO

  # @@protoc_insertion_point(class_scope:io_gphoto2.Photo)


# @@protoc_insertion_point(module_scope)
